language: generic

deploy:
  provider: s3
  access_key_id:
    secure: "l80DsDLWgnYkgJ8qWSoeG0CiqoGOB4Q1F15UAnpEgqWkQ0g/vrpPiYPC2Afa1cGrqakRQY+spgxy3NnFIcHnfqCHDvCBf67ghblmZPG3khwD4JKxN8pyeZgGburtqbpfE/a0BK6FSPQESgSiZs0yUlnSEM6jawdTIpPM6j6EEssdocy9TS7WGps9fvD7Gr1dIxcemiyHIfKbCU9EwMYqaiGPPxm19XyPoJ7AAqWfuqZW6U2bYl2K3uvbzkbzINhVJl28UCUp1j7nh8ljl/asnDwZ8tDLo7tLOw/oXvGoPZL1NE4tWvyTyzjs+HUK/EUYc+bTYYxRMIsJwve3bRxp9E4zaePtXJAevxDbdaB8CTa4R1Xm5LL2ZQpj1zoQPlRPs3j+pDyh3/8Mp5OJF0DoXalwHzy0ufjmW9o11mDXScwGheRiKPFjOIAntrh2Rbmcq54d360cgUMZuWGnDrpW2UM4RBewMB7ySumRLpOA2cuacpRfTGhVFwo7ZjyZZuckXwZKM6o5Z2ltVZioVrgQ2YIytt4h6FZXE3VDOtezjb2fxLpT2y57HZ3M8TCAmrJTG51FwuBZawn29eEEJl2RN1oxI6/CW92XDbYrvmshgALRf+VadeECU2IKCqV3pzHo651ORaN4PSH7dXjjmUR/gH9mW2VTBK/cMuEd4WLc5ys="
  secret_access_key:
    secure: "MIUOdM4ZcUTdpt9qiTKeyg5n02bVvlIkKrnu2ZUjNMdTebVsEKOJpx+ctXp3JqUNVyoAj2xP8e4pPdDdzDIWBkU3/jGVucy1W9g3lMTwcN6YScvBhIM3UOhCtgpy6gfBvb7So7OszQ1uYp53Yg7r/ZNFfwQy2cXDlKVT8WMu6hCg9jImtjFs5VnkvUuKcjdt9iDDc+InncKXGWzH0qV/99mAEUkYQZxkx/Y3hyZzLx3qGiHIblGumgBBIMrUUtm00XCj0OHEcZ9vNnElyBbwOSJOGzm7OQ1WYg9FwKEkCfac466fkQTIIdEBtRxmNeHWJWnicZ7z5o8Qq0ZuintwQKdDniBAotZ/hI9COAhihrwCYghA8mdw9GJKQix5MJlxNwtECnB9Y22w+B+zl6GZEs7GrWn7WDd50DPpsAVqBJunSgrJxhQO6+TIq8spKxfAdXL2jt+pnoAZQNVT+I1ttF1h1FEYUNwi/evvjwF32RlDpAu2fsQeDU06+0XEWw5iD/QEocr0EGkSx/6ltmSodetfKEs1LYkbyc6n3j6znDmSF3JLUS/HqS1a+jXdI1k8qXSeQLENoDFQDQJk3Znow2lEyNJDq8MWBH5gKiKE1pjnoSFGvgRNjwA6m+ieSbCvc/n877o3Q8zjATujiypmEhDIFYClIW21lfrZkcjUqY4="
  bucket: andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  default_text_charset: utf-8
  detect_encoding: true
  local_dir: build/
  upload_dir: projects/cube/
